variable "kubeconfig_path" {
  description = "Path to the Talos cluster's kubeconfig, generated by the proxmox-tofu / talosctl bootstrap."
  type        = string
  default     = "../../proxmox-tofu/_out/kubeconfig"
}

variable "namespace" {
  description = "Namespace to install clusterkeep-ui into. Must already exist , created by cluster-config, not here (see its clusterkeep-ui-namespaces.tf)."
  type        = string
  default     = "clusterkeep-dev-pub"
}

variable "image_repository" {
  description = "Registry + repository for the clusterkeep-ui image (the in-cluster Nexus docker-hosted repo, provisioned in cluster-config)."
  type        = string
  default     = "registry.talos.lab/clusterkeep-ui"
}

variable "image_tag" {
  description = "Fallback image tag, used only if no pushed tag matches image_tag_prefix yet (e.g. a brand-new environment). Normally tofu resolves the tag itself , see the external data source in clusterkeep-ui.tf."
  type        = string
}

variable "image_tag_prefix" {
  description = "Which branch's tag channel this environment tracks , \"DEV-\" or \"PREVIEW-\" (cluster-cli's branch-based tag prefixes, see ../../cluster-cli/README.md), or \"\" to pick the newest plain-numeric (release/main) tag. Every tofu apply deploys the newest pushed tag matching this."
  type        = string
  default     = "DEV-"
}

variable "ingress_hostname" {
  description = "Hostname the clusterkeep-ui UI will be served on via Ingress."
  type        = string
  default     = "clusterkeep.talos.lab"
}

variable "ingress_enabled" {
  description = "Whether to create a LAN Ingress for this instance. Disable for the prd instance , it's reached only via the Cloudflare Tunnel hitting its Service directly, and an Ingress would collide on ingress_hostname with the dev instance's."
  type        = bool
  default     = true
}

variable "image_pull_secret_name" {
  description = "Name of the imagePullSecret to use, if the Nexus docker-hosted repo requires auth. Created in cluster-config (see its clusterkeep-ui-namespaces.tf), not here , leave blank if the repo allows anonymous pulls."
  type        = string
  default     = ""
}
