name: sync-bastion

on:
  push:
    branches: ["**"]

concurrency:
  group: sync-bastion
  cancel-in-progress: true

jobs:
  sync:
    runs-on: [self-hosted]
    steps:
      - name: Sync all repos on the bastion
        run: sync-repos.sh
